export const planetData = {
  Sun: {
    name: "Sun",
    diameter: 1392700,
    rotation: "25-35 days",
    distance: 0,
    gravity: 274,
    temperature: 5500,
    moons: 0,
    icon: "☀️",
    color: "#FF6B35",
    description: "The Sun is the star at the center of our Solar System. It's a nearly perfect sphere of hot plasma, heated by nuclear fusion reactions in its core. The Sun radiates energy mostly as light, ultraviolet, and infrared radiation.",
    fact: "The Sun accounts for 99.86% of the mass in the Solar System."
  },
  Mercury: {
    name: "Mercury",
    diameter: 4879,
    rotation: "58.6 days",
    distance: 57.9,
    gravity: 3.7,
    temperature: 167,
    moons: 0,
    icon: "☿",
    color: "#6A6A92",
    description: "Mercury is the smallest planet in our Solar System and the closest to the Sun. Its surface is heavily cratered, resembling Earth's Moon. It has extreme temperature variations, from 430°C in the day to -180°C at night.",
    fact: "A year on Mercury (88 Earth days) is shorter than its day (176 Earth days)."
  },
  Venus: {
    name: "Venus",
    diameter: 12104,
    rotation: "243 days (retrograde)",
    distance: 108.2,
    gravity: 8.9,
    temperature: 464,
    moons: 0,
    icon: "♀",
    color: "#E89D65",
    description: "Venus is the second planet from the Sun and Earth's closest planetary neighbor. It has a thick atmosphere that traps heat in a runaway greenhouse effect, making it the hottest planet in our solar system.",
    fact: "Venus rotates in the opposite direction to most planets, meaning the Sun rises in the west and sets in the east."
  },
  Earth: {
    name: "Earth",
    diameter: 12756,
    rotation: "23.9 hours",
    distance: 149.6,
    gravity: 9.8,
    temperature: 15,
    moons: 1,
    icon: "🌍",
    color: "#4A99E9",
    description: "Earth is the third planet from the Sun and the only astronomical object known to harbor life. About 71% of Earth's surface is covered with water, with the remaining 29% consisting of continents and islands.",
    fact: "Earth is the only planet not named after a god in our Solar System."
  },
  Mars: {
    name: "Mars",
    diameter: 6792,
    rotation: "24.6 hours",
    distance: 227.9,
    gravity: 3.7,
    temperature: -65,
    moons: 2,
    icon: "♂",
    color: "#E27B58",
    description: "Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System. It's often called the 'Red Planet' due to the iron oxide on its surface giving it a reddish appearance.",
    fact: "Mars has the largest dust storms in the Solar System, sometimes engulfing the entire planet."
  },
  Jupiter: {
    name: "Jupiter",
    diameter: 142984,
    rotation: "9.9 hours",
    distance: 778.6,
    gravity: 24.8,
    temperature: -110,
    moons: 95,
    icon: "♃",
    color: "#E8C275",
    description: "Jupiter is the fifth planet from the Sun and the largest in the Solar System. It's a gas giant primarily composed of hydrogen and helium, with colorful cloud bands and the iconic Great Red Spot.",
    fact: "Jupiter's Great Red Spot is a storm that has been continuously observed for over 400 years."
  },
  Saturn: {
    name: "Saturn",
    diameter: 120536,
    rotation: "10.7 hours",
    distance: 1433.5,
    gravity: 10.4,
    temperature: -140,
    moons: 146,
    icon: "♄",
    color: "#E8B465",
    description: "Saturn is the sixth planet from the Sun and the second-largest in the Solar System, characterized by its spectacular ring system. Like Jupiter, it's a gas giant composed mostly of hydrogen and helium.",
    fact: "Saturn's rings are made up of billions of ice particles, ranging in size from tiny dust grains to house-sized chunks."
  },
  Uranus: {
    name: "Uranus",
    diameter: 51118,
    rotation: "17.2 hours (retrograde)",
    distance: 2872.5,
    gravity: 8.7,
    temperature: -195,
    moons: 27,
    icon: "♅",
    color: "#4FC3C3",
    description: "Uranus is the seventh planet from the Sun and the third-largest by diameter. It's unique among the planets for rotating on its side, with an axial tilt of 98 degrees.",
    fact: "Uranus was the first planet discovered with the use of a telescope, by William Herschel in 1781."
  },
  Neptune: {
    name: "Neptune",
    diameter: 49528,
    rotation: "16.1 hours",
    distance: 4495.1,
    gravity: 11.2,
    temperature: -200,
    moons: 16,
    icon: "♆",
    color: "#3066BE",
    description: "Neptune is the eighth and farthest known planet from the Sun. It's a dark, cold world with supersonic winds, and is similar in composition to Uranus. It was predicted mathematically before it was observed.",
    fact: "Neptune's winds are the fastest in the Solar System, reaching up to 2,100 km/h (1,300 mph)."
  }
};

export const cameraPositions = {
  Sun: [0, 8, 15],
  Mercury: [8, 2, 2],
  Venus: [13, 3, 3],
  Earth: [18, 5, 5],
  Mars: [26, 3, 7],
  Jupiter: [52, 10, 15],
  Saturn: [64, 10, 20],
  Uranus: [76, 6, 15],
  Neptune: [88, 6, 15],
  Overview: [0, 50, 120],
};